export const LOGIN_REQUEST = 'LOGIN/REQUEST';
export const LOGIN_SUCCESS = 'LOGIN/SUCCESS';
export const LOGIN_FAILURE = 'LOGIN/FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT/REQUEST';

export const RESET_PASSWORD = 'APP/RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'APP/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'APP/RESET_PASSWORD_FAIL';

export const SET_PASSWORD = 'APP/SET_PASSWORD';
export const SET_PASSWORD_SUCCESS = 'APP/SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_FAIL = 'APP/SET_PASSWORD_FAIL';
