export default {
  qualifiedLeads: [
    {
      id: 1,
      firstName: 'Tiger Nixon 1',
      lastName: 'Desigcafe',
      address: '12, Random street name Chennai, Tamil Nadu India 600064',
      phone: '+91 8939792845',
      email: 'jayaprasad.mohanan@gmail.com',
      date: '21/07/2019',
      time: '2:30 PM',
      status: 'scheduled',
    },
    {
      id: 2,
      firstName: 'Tiger Nixon 2',
      lastName: 'Desigcafe',
      address: '12, Random street name Chennai, Tamil Nadu India 600064',
      phone: '+91 8939792845',
      email: 'jayaprasad.mohanan@gmail.com',
      date: 'Not avaliable',
      time: '',
      status: 'unScheduled',
    },
    {
      id: 3,
      firstName: 'Tiger Nixon 3',
      lastName: 'Desigcafe',
      address: '12, Random street name Chennai, Tamil Nadu India 600064',
      phone: '+91 8939792845',
      email: 'jayaprasad.mohanan@gmail.com',
      date: '21/07/2019',
      time: '2:30 PM',
      status: 'scheduled',
    },
    {
      id: 4,
      firstName: 'Tiger Nixon 4',
      lastName: 'Desigcafe',
      address: '12, Random street name Chennai, Tamil Nadu India 600064',
      phone: '+91 8939792845',
      email: 'jayaprasad.mohanan@gmail.com',
      date: 'Not available',
      time: '',
      status: 'unScheduled',
    },
  ],
  broadcashLeads: [
    {
      id: 5,
      firstName: 'Tiger Nixon 5',
      lastName: 'Desigcafe',
      address: '12, Random street name Chennai, Tamil Nadu India 600064',
      phone: '+91 8939792845',
      email: 'jayaprasad.mohanan@gmail.com',
      date: '21/07/2019',
      time: '2:30 PM',
      status: 'scheduled',
    },
    {
      id: 6,
      firstName: 'Tiger Nixon 6',
      lastName: 'Desigcafe',
      address: '12, Random street name Chennai, Tamil Nadu India 600064',
      phone: '+91 8939792845',
      email: 'jayaprasad.mohanan@gmail.com',
      date: '21/07/2019',
      time: '2:30 PM',
      status: 'scheduled',
    },
    {
      id: 7,
      firstName: 'Tiger Nixon 7',
      lastName: 'Desigcafe',
      address: '12, Random street name Chennai, Tamil Nadu India 600064',
      phone: '+91 8939792845',
      email: 'jayaprasad.mohanan@gmail.com',
      date: '21/07/2019',
      time: '2:30 PM',
      status: 'scheduled',
    },
    {
      id: 8,
      firstName: 'Tiger Nixon 8',
      lastName: 'Desigcafe',
      address: '12, Random street name Chennai, Tamil Nadu India 600064',
      phone: '+91 8939792845',
      email: 'jayaprasad.mohanan@gmail.com',
      date: '21/07/2019',
      time: '2:30 PM',
      status: 'unScheduled',
    },
  ],
};
