export const LOGIN_REQUEST = 'LOGIN/REQUEST';
export const LOGIN_SUCCESS = 'LOGIN/SUCCESS';
export const LOGIN_FAILED = 'LOGIN/FAILED';

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE/REQUEST';
export const EDIT_PROFILE_SUCCUESS = 'EDIT_PROFILE/SUCCESS';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE/FAILED';
