export default [
  {
    id: 1,
    name: 'Tiger Nixon',
    branch: '1MG Experience Center',
    email: 'colton_champlin@designcafe.com',
    type: 'Designer Freelance',
  },
  {
    id: 2,
    name: 'asdfas',
    branch: 'Name',
    email: 'asdfasdf@gmial.com',
    type: 'asdfadsf',
  },
  {
    id: 3,
    name: 'asdfas',
    branch: 'Name',
    email: 'asdfasdf@gmial.com',
    type: 'asdfadsf',
  },
  {
    id: 4,
    name: 'asdfas',
    branch: 'Name',
    email: 'asdfasdf@gmial.com',
    type: 'asdfadsf',
  },
  {
    id: 5,
    name: 'asdfas',
    branch: 'Name',
    email: 'asdfasdf@gmial.com',
    type: 'asdfadsf',
  },
  {
    id: 6,
    name: 'asdfas',
    branch: 'Name',
    email: 'asdfasdf@gmial.com',
    type: 'asdfadsf',
  },
  {
    id: 7,
    name: 'asdfas',
    branch: 'Name',
    email: 'asdfasdf@gmial.com',
    type: 'asdfadsf',
  },
  {
    id: 8,
    name: 'asdfas',
    branch: 'Name',
    email: 'asdfasdf@gmial.com',
    type: 'asdfadsf',
  },
  {
    id: 9,
    name: 'asdfas',
    branch: 'Name',
    email: 'asdfasdf@gmial.com',
    type: 'asdfadsf',
  },
  {
    id: 10,
    name: 'asdfas',
    branch: 'Name',
    email: 'asdfasdf@gmial.com',
    type: 'asdfadsf',
  },
  {
    id: 11,
    name: 'asdfas',
    branch: 'Name',
    email: 'asdfasdf@gmial.com',
    type: 'asdfadsf',
  },
];
